// <auto-generated />
namespace ProyectoFinalProgramacionIII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clienteMmg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clienteMmg));
        
        string IMigrationMetadata.Id
        {
            get { return "201707241335285_clienteMmg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
